exclude: ^(.github|.changes|docs/|boto3/compat.py|boto3/data|CHANGELOG.rst)
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d1b833175a5d08a925900115526febd8fe71c98e  # frozen: v0.15.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
