exclude: ^(.github|.changes|docs/|boto3/compat.py|boto3/data|CHANGELOG.rst)
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 745be0411e3c150e246d527e531e5a221b8c3462  # frozen: v0.15.19
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
