[project]
name = "boto3"
dynamic = ["version"]
description = "The AWS SDK for Python"
readme = "README.rst"
authors = [
    { name = "Amazon Web Services"}
]
requires-python=">= 3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 2 - Beta",
]
dependencies = [
    "botocore>=1.43.75,<1.44.0",
    "jmespath>=0.7.1,<2.0.0",
    "s3transfer>=0.19.0,<0.20.0",
]

[project.optional-dependencies]
crt = ["botocore[crt]>=1.21.0,<2.0a0"]

[project.urls]
Homepage = "https://github.com/boto/boto3"
Documentation = "https://docs.aws.amazon.com/boto3/latest/"
Source = "https://github.com/boto/boto3"

[build-system]
requires = ["setuptools>=84"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["boto3*"]

[tool.setuptools.dynamic]
version = { attr = "boto3.__version__" }

[tool.setuptools.package-data]
boto3 = ["data/aws/resources/*.json", "examples/*.rst"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Format same as Black.
line-length = 79
indent-width = 4

target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "E4", # pycodestyle
    "E7", # pycodestyle
    "E9", # pycodestyle
    "F", # pyflakes
    "G", # flake8-logging-format
    "I", # isort
    "UP", # pyupgrade
]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings, spaces for indents
# and trailing commas.
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = false
docstring-code-line-length = "dynamic"
